// Seed data plumbing. Two sources, strictly separated:
//
//   • loadDevSeed()  — the REAL converted Nara export, for LOCAL dev only. It's
//     gitignored and generated by `pnpm nara`. Loaded via import.meta.glob so a
//     missing file is "no seed" (not a build error), and gated on
//     import.meta.env.DEV so it is tree-shaken out of the production bundle
//     entirely — the real baby data can never reach the public origin or the
//     gallery demo.
//   • demoSeed() (lib/demo.ts) — a small SYNTHETIC baby, for the public
//     "Try it live" demo. Never real data.

import type { SproutsEvent } from './events'

export interface SeedData {
  /** child.create (+ optional child.update) events → children.jsonl */
  children: SproutsEvent[]
  /** childId → that child's entry.log events → logs/<childId>.jsonl */
  logs: Record<string, SproutsEvent[]>
}

export function loadDevSeed(): SeedData | null {
  if (!import.meta.env.DEV) return null
  const mods = import.meta.glob('../data/seed.dev.json', { eager: true }) as Record<string, { default: SeedData }>
  const first = Object.values(mods)[0]
  return first?.default ?? null
}
